apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-spot-handler
  namespace: castai-agent
spec:
  selector:
    matchLabels:
      name: azure-spot-handler
  template:
    metadata:
      labels:
        name: azure-spot-handler
    spec:
      serviceAccount: azure-spot-handler
      tolerations:
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        scheduling.cast.ai/spot: true
      containers:
        - name: azure-spot-handler
          image: handlertestregistry.azurecr.io/matas/castai-spot-handler:v0.0.1-local
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POLL_INTERVAL_SECONDS
              value: "1"
            - name: PPROF_PORT
              value: "6060"
            - name: API_URL
              value: ""
            - name: API_KEY
              value: ""
            - name: CLUSTER_ID
              value: ""
      terminationGracePeriodSeconds: 30
