apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-spot-handler
  namespace: castai-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-spot-handler
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-spot-handler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-spot-handler
subjects:
  - kind: ServiceAccount
    name: azure-spot-handler
    namespace: castai-agent
